### ISSUE TITLE
Methods never awaited

### ISSUE THREAD

**Issue by ebarrere** [frwickst/pyhuum#9]
I'm new to python so this may well be a simple issue. That said I am completely unable to use the module as provided. I am attempting to use it directly (rather than via homekit), so this could be part of the problem.

Environment is a local venv set up as follows.
```
(.env)[elliott@shiny light_control (aiotest ✗)]$ which python
/Users/elliott/Documents/code/personal/light_control/.env/bin/python
(.env)[elliott@shiny light_control (aiotest ✗)]$ python --version
Python 3.11.10
(.env)[elliott@shiny light_control (aiotest ✗)]$ pip list
Package            Version
------------------ ---------
aiohappyeyeballs   2.4.3
aiohttp            3.10.9
aiosignal          1.3.1
annotated-types    0.7.0
attrs              24.2.0
certifi            2024.8.30
charset-normalizer 3.3.2
frozenlist         1.4.1
huum               0.7.10
idna               3.10
mashumaro          3.13.1
multidict          6.1.0
pip                24.2
pydantic           2.9.2
pydantic_core      2.23.4
pydantic-settings  2.5.2
python-dotenv      1.0.1
requests           2.32.3
setuptools         74.1.2
typing_extensions  4.12.2
urllib3            2.2.3
yarl               1.13.1
```

First of all, the README says to use `from huum import Huum`, but this does not work for me; I need `from huum.huum import Huum`. Then, when calling any `huum.method` I receive a variation of the following error:

```
(.env)[elliott@shiny light_control (aiotest ✗)]$ ./light_control.py
/Users/elliott/Documents/code/personal/light_control/./light_control.py:51: RuntimeWarning: coroutine 'Huum.open_session' was never awaited
  huum.open_session()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
<coroutine object Huum.status at 0x10c659990>
/Users/elliott/Documents/code/personal/light_control/./light_control.py:56: RuntimeWarning: coroutine 'Huum.status' was never awaited
  print(huum.status())
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
<coroutine object Huum.status at 0x10c659990>
^CTraceback (most recent call last):
  File "/Users/elliott/Documents/code/personal/light_control/./light_control.py", line 55, in <module>
    time.sleep(SLEEP_TIME)
KeyboardInterrupt
```

This happens whether I call `huum.open_session()`, `huum.status()` or `huum.turn_on`.

I have rewritten the code to use the `requests` module instead of `aiohttp` so I can continue to use the core functionality, but I'd much prefer to use it "as written".

Let me know if you need any more detail.

**Comment by frwickst** [comment]
The reason why you are getting these errors is because the entire library is written in a async manner. Since you are not running in a event loop, you will not be able to call those functions directly, but you will need to make sure to be able to run async code first.
This is not covered in the readme, sorry for that, but this is generally something that should be clear quite quickly when running the code as well.
The code will not be rewritten to user `requests`, since this library was mainly created to be used with Home Assistant (not HomeKit) and they use `aiohttp` as their client that I can just pass into the library. The readme could be made better here for sure with some extra information about the `aiohttp` requirement, you can install that with `pip install huum[aiohttp]` as the `aiohttp` is seen as a extra here as it is already included in Home Assistant.

So what you need to do to get this running is the following:
1. Install the library with `pip install huum[aiohttp]`
2. Run something in the lines of:
```
from huum.huum import Huum
import asyncio

async def turn_on_the_sauna():
    huum = Huum(username="REPLACE", password="REPLACE")
    await huum.open_session()
    await huum.turn_on(80)

asyncio.run(turn_on_the_sauna())
```

Note that this is of course a very simplified example again, and you most likely want to do a bunch of other stuff as well. Asyncio should probably run your entire application and not just call a function. And yes, you are correct that it should have been `from huum.huum import Huum` and not just `from huum import Huum` I'll change the readme when I get the time.

The code above was tested (with credentials replaces) and worked on Python 3.12.

**Comment by ebarrere** [comment]
Thanks for the advice, it is very helpful!
